### ISSUE TITLE
Fixed label (CON-257)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#200]
I have a device with two lights, I would like to assign a default name to the device and to each light

with mfg_tool I use this command

./mfg_tool.py -cn "Lights" -v 0xFFF2 -p 0x8001 --fixed-labels "0/name/Lights" "1/name/CH_1" "2/name/CH_2"

and for each endpoint I add:

fixed_label::config_t fixed_config;
fixed_config.cluster_revision = 1;
cluster::fixed_label::create(endpoint, &fixed_config, CLUSTER_FLAG_SERVER);

but it does not work
where am i wrong?

**Comment by jadhavrohit924** [comment]
@stefano055415 Did you created `LabelList` attribute for fixed label cluster?

**Comment by stefano055415** [comment]
@jadhavrohit924 

with LabelList do you mean this?

esp_matter_attr_val_t val = esp_matter_array((uint8_t*)"MyFixedLabel", strlen("MyFixedLabel"), 1);
    err = attribute::update(1, FixedLabel::Id, FixedLabel::Attributes::LabelList::Id, &val);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Fixed label failed: %d", err);
    }

**Comment by stefano055415** [comment]
@jadhavrohit924 

Because from the mfg_tool documentation I thought it was enough to use this:

./mfg_tool.py -cn "Lights" -v 0xFFF2 -p 0x8001 --fixed-labels "0/name/Lights" "1/name/CH_1" "2/name/CH_2"

"endpoint_id/key/value"

although I don't quite understand what the key refers to

**Comment by jonsmirl** [comment]
This issue talks about it
https://github.com/espressif/esp-matter/issues/119

**Comment by shubhamdp** [comment]
Fixed labels, localization configuration, and time format configurations clusters are clubbed together into `DeviceInfoProvider`, and we do have an implementation for that [ESP32DeviceInfoProvider](https://github.com/project-chip/connectedhomeip/blob/master/src/platform/ESP32/ESP32DeviceInfoProvider.h), but we haven't integrated that with esp-matter.

When implementing localization configuration, and time format configurations clusters I hit https://github.com/espressif/esp-matter/issues/148 and I left it there. Since will be releasing the fix for #148 sooner. I'll push this changes out after rebasing.

**Comment by dhrishi** [comment]
@stefano055415 We have pushed the fix to this issue. Please pull the latest code and give it a try and close the issue if it works :-)

**Comment by shubhamdp** [comment]
Hi @stefano055415, we have integrated the `DeviceInfoProvider` into esp-matter https://github.com/espressif/esp-matter/commit/8f51120f383753629d49a57c96b083e684536f9b.

To use it
- Enable `CONFIG_ENABLE_ESP32_DEVICE_INFO_PROVIDER` config option, please find more details in [menuconfig options](https://docs.espressif.com/projects/esp-matter/en/latest/esp32/certification.html#menuconfig-options) section.
- Generate a factory partition with fixed labels using `mfg_tool.py`
- You will have to add some code for fixed label cluster. I have used the below to test things.
    ```
    cluster::fixed_label::config_t fl_config;
    cluster_t *fl_cluster = cluster::fixed_label::create(endpoint, &fl_config, CLUSTER_FLAG_SERVER);

    cluster::localization_configuration::config_t lc_config;
    cluster_t *lc_cluster = cluster::localization_configuration::create(endpoint, &lc_config, CLUSTER_FLAG_SERVER);
         
    cluster::time_format_localization::config_t tfl_config;
    cluster_t *tfl_cluster = cluster::time_format_localization::create(endpoint, &tfl_config, CLUSTER_FLAG_SERVER, 0x01);
    ```

**Comment by shubhamdp** [comment]
Please give it a try and let us know if you face more issues

**Comment by stefano055415** [comment]
@shubhamdp @dhrishi 

Something does not work...

I tried both google home and apple home

and i still don't see the fixed name

I enabled the CONFIG_ENABLE_ESP32_DEVICE_INFO_PROVIDER

for each endpoint I added

cluster::fixed_label::config_t fl_config;
cluster_t *fl_cluster = cluster::fixed_label::create(endpoint, &fl_config, CLUSTER_FLAG_SERVER);

cluster::localization_configuration::config_t lc_config;
cluster_t *lc_cluster = cluster::localization_configuration::create(endpoint, &lc_config, CLUSTER_FLAG_SERVER);
     
cluster::time_format_localization::config_t tfl_config;
cluster_t *tfl_cluster = cluster::time_format_localization::create(endpoint, &tfl_config, CLUSTER_FLAG_SERVER, 0x01);

and i created the partition like this

./mfg_tool.py -cn "Test" -v 0xFFF1 -p 0x8000 --pai \
   -k ../../connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Key.pem \
   -c ../../connectedhomeip/connectedhomeip/credentials/test/attestation/Chip-Test-PAI-FFF2-8001-Cert.pem \
   -cd ../../connectedhomeip/connectedhomeip/credentials/test/certification-declaration/Chip-Test-CD-FFF2-8001.der \
   --vendor-name "test_vendor" --product-name "test_name" --serial-num "12345678" \
   --hw-ver-str "2.0.0" \
   --passcode 29290158 --discriminator 3425 \
   --csv extra_nvs_key_config.csv --mcsv extra_nvs_key_value.csv \
   --fixed-labels "0/fixedname/Test"  "1/fixedname/CH_1" "2/fixedname/CH_2" "3/fixedname/CH_3" "4/fixedname/CH_4"

**Comment by stefano055415** [comment]
The partition I think is created correctly because I can see all the other values ​​vendor_name, product-name,serial-num,hw-version...

**Comment by stefano055415** [comment]
@shubhamdp 

you are right with chip-tool i can read the fixed label

CHIP:TOO: Endpoint: 2 Cluster: 0x0000_0040 Attribute 0x0000_0000 DataVersion: 21388564
CHIP:TOO:   label list: 1 entries
CHIP:TOO:     [1]: {
CHIP:TOO:       Label: fixedname
CHIP:TOO:       Value: CH_2
CHIP:TOO:      }

but how do I get the names to display correctly in google home and apple home?

I tried with the bridge example and it works

Is it possible they haven't implemented this feature?

**Comment by shubhamdp** [comment]
Fixed Label, User Label, Localization Configuration, Time Format Localization clusters are unsupported in [Google Home](https://developers.home.google.com/matter/get-started#unsupported_features) :-(

**Comment by stefano055415** [comment]
@shubhamdp 

I saw thanks too bad

I close the ticket pending developments

Thank you
