### ISSUE TITLE
Test Harness TC-ACE-1.5 (CON-488)

### ISSUE THREAD

**Issue by stefano055415** [espressif/esp-matter#383]
When I try to run the TC-ACE-1.5 test the test crashes

Executing Test Step: Commission from TH2

<img width="1321" alt="Screenshot 2023-05-12 at 10 34 14" src="https://github.com/espressif/esp-matter/assets/4798738/005784e8-62c2-4aab-95ed-aeb209b6fc58">

fails to do the second commissioning even though the window is open

Do I have to set something special?

Thank you

**Comment by wqx6** [comment]
Hi, @stefano055415 Could you provide the log of the TH instead of the error picture? BTW, are you using minimal mdns or platform mdns on ESP32?

**Comment by stefano055415** [comment]
@wqx6 

I think I understand the problem.

I have to run: ./chip-all-clusters-app
on raspberry

while the test starts to use it as the second TH

**Comment by wqx6** [comment]
The WebUI will start another TH automatically. You don't need another raspberry. Could you please provide the log which can be downloaded from the WebUI? I can't know the reason without the log.

**Comment by esterdv** [comment]
@wqx6 I also encountered the same issue when running the test. Please see attached logs.
[TC-ACE_2023_5_16_15_5_6.log](https://github.com/espressif/esp-matter/files/11485067/TC-ACE_2023_5_16_15_5_6.log)

**Comment by stefano055415** [comment]
@wqx6 @esterdv  If I don't start a second TH this is the result

[TC-ACE-1_5_run_2023_5_16_9_46_47.log](https://github.com/espressif/esp-matter/files/11485352/TC-ACE-1_5_run_2023_5_16_9_46_47.log)

**Comment by wqx6** [comment]
@stefano055415 In your log, the first TH pairs the DUT with the passcode `19628801` and opens the basic commissioning window in Test Step 2.
```
CHIPTOOL   | 2023-05-16 07:47:10.085820 | [1684223228.978864][23:30] CHIP:DMG: 			CommandPathIB =
CHIPTOOL   | 2023-05-16 07:47:10.087627 | [1684223228.978880][23:30] CHIP:DMG: 			{
CHIPTOOL   | 2023-05-16 07:47:10.089287 | [1684223228.978895][23:30] CHIP:DMG: 				EndpointId = 0x0,
CHIPTOOL   | 2023-05-16 07:47:10.101486 | [1684223228.978910][23:30] CHIP:DMG: 				ClusterId = 0x3c,
CHIPTOOL   | 2023-05-16 07:47:10.102975 | [1684223228.978924][23:30] CHIP:DMG: 				CommandId = 0x1,
CHIPTOOL   | 2023-05-16 07:47:10.104173 | [1684223228.978937][23:30] CHIP:DMG: 			},
```
Then the TH2 tries to pair the DUT with this QR-Code `MT:-24J0AFN00KA0648G00`
```
./chip-tool payload parse-setup-payload MT:-24J0AFN00KA0648G00                                                                                          [1684289362.931186][3435807:3435807] CHIP:SPL: Parsing base38Representation: MT:-24J0AFN00KA0648G00
[1684289362.931526][3435807:3435807] CHIP:SPL: Version:             0
[1684289362.931530][3435807:3435807] CHIP:SPL: VendorID:            65521
[1684289362.931532][3435807:3435807] CHIP:SPL: ProductID:           32769
[1684289362.931535][3435807:3435807] CHIP:SPL: Custom flow:         0    (STANDARD)
[1684289362.931538][3435807:3435807] CHIP:SPL: Discovery Bitmask:   0x04 (On IP network)
[1684289362.931540][3435807:3435807] CHIP:SPL: Long discriminator:  3840   (0xf00)
[1684289362.931542][3435807:3435807] CHIP:SPL: Passcode:            20202021
```
The Passcode is 20202021 in this QRCode. TH2 cannot commission the DUT with the wrong passcode. It is a TH issue. Could you please tell me the version of your TH and try with the latest TH version?

**Comment by wqx6** [comment]
@esterdv Your error is different from the error of @stefano055415. In your log, the TH2 is using the right QRCode to pair the device, but it fails in Attestation Verification. The error code is 101(PaaNotFound). But TH1 can pair the DUT successfully so I guess that the TH2 doesn't use the paa_trusted_root_path that is used by TH1. It is still the TH issue. Can you please use the latest TH version and try again? If there is still the same issue, please file an issue in [chip-certification-tool](https://github.com/CHIP-Specifications/chip-certification-tool).

**Comment by esterdv** [comment]
@wqx6 Thank you for looking into this and directing me to the chip-certification-tool page. It looks like the error is a known issue and we just need to apply a patch. Thank you again!

**Comment by stefano055415** [comment]
@wqx6 

Version: v2.7-official-TE
Sha: 821e3f8

it is the version that is indicated on the csa documentation

**Comment by wqx6** [comment]
I think there was still some issues for this test case on TH-v2.7. https://github.com/CHIP-Specifications/chip-certification-tool/issues/674, The latest TH should have fixed it.

**Comment by stefano055415** [comment]
@wqx6 

the problem is that i don't have access for this repo

**Comment by stefano055415** [comment]
@wqx6

Could you please link the latest TH image of the raspberry?

Thank you

**Comment by stefano055415** [comment]
@wqx6 

it is possible that the test does not work because the default values ​​are fixed in the  [Test_TC_ACE_1_5.yaml](https://github.com/espressif/connectedhomeip/blob/82db97695c2c899cc130c2d6a0d72b3c92c144db/src/app/tests/suites/certification/Test_TC_ACE_1_5.yaml)

**Comment by VaishaliAvhale** [comment]
@stefano055415 This is a semi-automated test case you have to execute some steps manually please check the semi-automated test case execution section in the below document and retest the TC.
[Matter_TH User Guide.pdf](https://github.com/espressif/esp-matter/files/12844664/Matter_TH.User.Guide.pdf)
- Use the latest TH version (i.e TH Fall2023)
- If still does not work please attach the device, TH, and TH chip-tool log here

**Comment by VaishaliAvhale** [comment]
For release/v1.1 certification you have test this TC manually please refer release/v1.1 verification document and execute it manually.
Pls refer to the “TCSummary” sheet of Verification  doc for the list of TCs to execute for release/v1.1 certification. There you can find more details about the TC means how to execute it and which PICS needed for execution of particular TC

**Comment by PhLuReh** [comment]
I really don't get to the point. I tried to figure out, how the things work, but did not succeed. After reading through the [TC_ACE_1-5](https://github.com/espressif/connectedhomeip/blob/v1.1.0.1/src/app/tests/suites/certification/Test_TC_ACE_1_5.yaml), I tried to manually execute the following steps:
```
./chip-tool pairing ble-wifi 1 SSID PASSWD 91436417 1862
./chip-tool operationalcredentials read CurrentFabricIndex 1
# reads CurrentFabricIndex: 1
./chip-tool administratorcommissioning open-commissioning-window 360 'hex:b96170aae803346884724fe9a3b287c30330c2a660375d17bb205a8cf1aecb350457f8ab79ee253ab6a8e46bb09e543ae422736de501e3db37d441fe344920d09548e4c18240630c4ff4913c53513839b7c07fcc0627a1b8573a149fcd1fa466cf' 3840 1000 "SPAKE2P Key SALT" 1 0 --timedInteractionTimeoutMs 30000
# Commissioning window opened on the DUT
```

Even the DUT is advertising, the next command I does not succeed (like the TH did not). Here's a excerpt from the DUT log:
```
I (5789122) chip[DIS]: Advertise operational node 49B67B9CEE0369C6-0000000000000001                                                                                      I (5789122) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: 49B67B9CEE0369C6-0000000000000001.
I (5789142) chip[DIS]: mDNS service published: _matter._tcp
I (5789142) app_main: advertise operational done
I (5789332) app_task: window 0 identification remaining time: -1 (segments: 0x0)
```

Starting with the one from the TC `./chip-tool pairing code-paseonly 2 "MT:-24J0AFN00KA0648G00" --commissioner-name beta` failing in a discovery problem:
```
[1707483477.997825][573319:573319] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1707483478.003409][573319:573319] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_factory.ini
[1707483478.003665][573319:573319] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_config.ini
[1707483478.003771][573319:573319] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_counters.ini
[1707483478.004125][573319:573319] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-Ndw09E)
[1707483478.004743][573319:573319] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1707483478.004800][573319:573319] CHIP:DL: NVS set: chip-counters/reboot-count = 9039 (0x234F)
[1707483478.005651][573319:573319] CHIP:DL: Got Ethernet interface: eth0
[1707483478.006206][573319:573319] CHIP:DL: Found the primary Ethernet interface:eth0
[1707483478.006793][573319:573319] CHIP:DL: Got WiFi interface: wlan0
[1707483478.006858][573319:573319] CHIP:DL: Failed to reset WiFi statistic counts
[1707483478.006910][573319:573319] CHIP:IN: UDP::Init bind&listen port=0
[1707483478.007019][573319:573319] CHIP:IN: UDP::Init bound to port=41258
[1707483478.007042][573319:573319] CHIP:IN: BLEBase::Init - setting/overriding transport
[1707483478.007059][573319:573319] CHIP:IN: TransportMgr initialized
[1707483478.007091][573319:573319] CHIP:FP: Initializing FabricTable from persistent storage
[1707483478.007265][573319:573319] CHIP:TS: Last Known Good Time: 2023-04-11T06:55:26
[1707483478.008794][573319:573319] CHIP:FP: Fabric index 0x1 was retrieved from storage. Compressed FabricId 0x49B67B9CEE0369C6, FabricId 0x0000000000000001, NodeId 0x000000000001B669, VendorId 0xFFF1
[1707483478.009259][573319:573319] CHIP:FP: Fabric index 0x2 was retrieved from storage. Compressed FabricId 0xE2B270F8EA256EE6, FabricId 0x0000000000000002, NodeId 0x000000000001B669, VendorId 0xFFF1
[1707483478.011764][573319:573319] CHIP:ZCL: Using ZAP configuration...
[1707483478.015596][573319:573319] CHIP:DL: Avahi client registered
[1707483478.017025][573319:573319] CHIP:CTL: System State Initialized...
[1707483478.017153][573319:573319] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483478.017207][573319:573319] CHIP:CTL: Setting attestation nonce to random value
[1707483478.017243][573319:573319] CHIP:CTL: Setting CSR nonce to random value
[1707483478.017548][573319:573321] CHIP:DL: CHIP task running
[1707483478.017818][573319:573321] CHIP:DL: HandlePlatformSpecificBLEEvent 32784
[1707483478.018148][573319:573321] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483478.018193][573319:573321] CHIP:CTL: Setting attestation nonce to random value
[1707483478.018347][573319:573321] CHIP:CTL: Setting CSR nonce to random value
[1707483478.019247][573319:573321] CHIP:CTL: Generating NOC
[1707483478.020234][573319:573321] CHIP:FP: Validating NOC chain
[1707483478.021963][573319:573321] CHIP:FP: NOC chain validation successful
[1707483478.022117][573319:573321] CHIP:FP: Updated fabric at index: 0x2, Node ID: 0x000000000001B669
[1707483478.022147][573319:573321] CHIP:TS: Last Known Good Time: 2023-04-11T06:55:26
[1707483478.022166][573319:573321] CHIP:TS: New proposed Last Known Good Time: 2021-01-01T00:00:00
[1707483478.022184][573319:573321] CHIP:TS: Retaining current Last Known Good Time
[1707483478.024838][573319:573321] CHIP:FP: Metadata for Fabric 0x2 persisted to storage.
[1707483478.027696][573319:573321] CHIP:TS: Committing Last Known Good Time to storage: 2023-04-11T06:55:26
[1707483478.030211][573319:573321] CHIP:CTL: Joined the fabric at index 2. Fabric ID is 0x0000000000000002 (Compressed Fabric ID: E2B270F8EA256EE6)
[1707483478.047479][573319:573321] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483478.047526][573319:573321] CHIP:CTL: Starting commissioning discovery over DNS-SD
[1707483478.058888][573319:573321] CHIP:DL: Avahi browse: cache new
[1707483478.059018][573319:573321] CHIP:DL: Avahi browse: cache new
[1707483478.059146][573319:573321] CHIP:DL: Avahi browse: cache exhausted
[1707483479.062214][573319:573321] CHIP:DL: Avahi browse: all for now
[1707483479.066641][573319:573321] CHIP:DL: Avahi resolve found
[1707483479.066758][573319:573321] CHIP:DIS: Discovered node:
[1707483479.066801][573319:573321] CHIP:DIS:    Hostname: E89F6DE633D8
[1707483479.066854][573319:573321] CHIP:DIS:    IP Address #1: fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8
[1707483479.066897][573319:573321] CHIP:DIS:    Port: 5540
[1707483479.066938][573319:573321] CHIP:DIS:    Mrp Interval idle: not present
[1707483479.066979][573319:573321] CHIP:DIS:    Mrp Interval active: not present
[1707483479.067019][573319:573321] CHIP:DIS:    TCP Supported: 1
[1707483479.067060][573319:573321] CHIP:DIS:    Vendor ID: 5186
[1707483479.067100][573319:573321] CHIP:DIS:    Product ID: 4369
[1707483479.067140][573319:573321] CHIP:DIS:    Long Discriminator: 3840
[1707483479.067180][573319:573321] CHIP:DIS:    Pairing Hint: 36
[1707483479.067219][573319:573321] CHIP:DIS:    Instance Name: 20BF59E74C653CEF
[1707483479.067259][573319:573321] CHIP:DIS:    Commissioning Mode: 2
[1707483479.068827][573319:573321] CHIP:DL: Avahi resolve found
[1707483479.068939][573319:573321] CHIP:DIS: Discovered node:
[1707483479.068981][573319:573321] CHIP:DIS:    Hostname: E89F6DE633D8
[1707483479.069032][573319:573321] CHIP:DIS:    IP Address #1: fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8
[1707483479.069075][573319:573321] CHIP:DIS:    Port: 5540
[1707483479.069114][573319:573321] CHIP:DIS:    Mrp Interval idle: not present
[1707483479.069154][573319:573321] CHIP:DIS:    Mrp Interval active: not present
[1707483479.069193][573319:573321] CHIP:DIS:    TCP Supported: 1
[1707483479.069233][573319:573321] CHIP:DIS:    Vendor ID: 5186
[1707483479.069273][573319:573321] CHIP:DIS:    Product ID: 4369
[1707483479.069313][573319:573321] CHIP:DIS:    Long Discriminator: 3840
[1707483479.069352][573319:573321] CHIP:DIS:    Pairing Hint: 36
[1707483479.069392][573319:573321] CHIP:DIS:    Instance Name: 20BF59E74C653CEF
[1707483479.069437][573319:573321] CHIP:DIS:    Commissioning Mode: 2
```

This command is hanging for long time and finally failing with:
```
[1707483508.077044][573319:573321] CHIP:CTL: Discovery timed out
[1707483508.077147][573319:573321] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483508.077208][573319:573321] CHIP:TOO: Secure Pairing Failed
[1707483508.077754][573319:573319] CHIP:CTL: Shutting down the commissioner
[1707483508.077825][573319:573319] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483508.077881][573319:573319] CHIP:CTL: Shutting down the controller
[1707483508.077939][573319:573319] CHIP:IN: Expiring all sessions for fabric 0x2!!
[1707483508.077991][573319:573319] CHIP:FP: Forgetting fabric 0x2
[1707483508.078061][573319:573319] CHIP:TS: Pending Last Known Good Time: 2023-04-11T06:55:26
[1707483508.078488][573319:573319] CHIP:TS: Previous Last Known Good Time: 2023-04-11T06:55:26
[1707483508.078548][573319:573319] CHIP:TS: Reverted Last Known Good Time to previous value
[1707483508.078685][573319:573319] CHIP:CTL: Shutting down the commissioner
[1707483508.078745][573319:573319] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483508.078795][573319:573319] CHIP:CTL: Shutting down the controller
[1707483508.078846][573319:573319] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
[1707483508.080670][573319:573319] CHIP:DMG: All ReadHandler-s are clean, clear GlobalDirtySet
[1707483508.080839][573319:573319] CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
[1707483508.080918][573319:573319] CHIP:FP: Shutting down FabricTable
[1707483508.080975][573319:573319] CHIP:TS: Pending Last Known Good Time: 2023-04-11T06:55:26
[1707483508.081259][573319:573319] CHIP:TS: Previous Last Known Good Time: 2023-04-11T06:55:26
[1707483508.081316][573319:573319] CHIP:TS: Reverted Last Known Good Time to previous value
[1707483508.081723][573319:573319] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-bIen8v)
[1707483508.082884][573319:573319] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1707483508.082999][573319:573319] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
[1707483508.083052][573319:573319] CHIP:DL: Inet Layer shutdown
[1707483508.083094][573319:573319] CHIP:DL: BLE shutdown
[1707483508.083138][573319:573319] CHIP:DL: System Layer shutdown
[1707483508.083593][573319:573319] CHIP:TOO: Run command failure: examples/chip-tool/commands/pairing/PairingCommand.cpp:240: CHIP Error 0x00000003: Incorrect state
```

I then tried to pair with the original passcode from the certificate credentials:
```
ubuntu@ubuntu:~/apps$ ./chip-tool pairing onnetwork 2 91436417 --commissioner-name beta
[1707483781.740699][573348:573348] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
[1707483781.746142][573348:573348] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_factory.ini
[1707483781.746401][573348:573348] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_config.ini
[1707483781.746511][573348:573348] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_counters.ini
[1707483781.746879][573348:573348] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-umLnbC)
[1707483781.747516][573348:573348] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1707483781.747572][573348:573348] CHIP:DL: NVS set: chip-counters/reboot-count = 9044 (0x2354)
[1707483781.748396][573348:573348] CHIP:DL: Got Ethernet interface: eth0
[1707483781.749038][573348:573348] CHIP:DL: Found the primary Ethernet interface:eth0
[1707483781.749604][573348:573348] CHIP:DL: Got WiFi interface: wlan0
[1707483781.749669][573348:573348] CHIP:DL: Failed to reset WiFi statistic counts
[1707483781.749721][573348:573348] CHIP:IN: UDP::Init bind&listen port=0
[1707483781.749826][573348:573348] CHIP:IN: UDP::Init bound to port=60004
[1707483781.749847][573348:573348] CHIP:IN: BLEBase::Init - setting/overriding transport
[1707483781.749864][573348:573348] CHIP:IN: TransportMgr initialized
[1707483781.749896][573348:573348] CHIP:FP: Initializing FabricTable from persistent storage
[1707483781.750064][573348:573348] CHIP:TS: Last Known Good Time: 2023-04-11T06:55:26
[1707483781.751667][573348:573348] CHIP:FP: Fabric index 0x1 was retrieved from storage. Compressed FabricId 0x49B67B9CEE0369C6, FabricId 0x0000000000000001, NodeId 0x000000000001B669, VendorId 0xFFF1
[1707483781.752112][573348:573348] CHIP:FP: Fabric index 0x2 was retrieved from storage. Compressed FabricId 0xE2B270F8EA256EE6, FabricId 0x0000000000000002, NodeId 0x000000000001B669, VendorId 0xFFF1
[1707483781.754490][573348:573348] CHIP:ZCL: Using ZAP configuration...
[1707483781.758077][573348:573348] CHIP:DL: Avahi client registered
[1707483781.759339][573348:573348] CHIP:CTL: System State Initialized...
[1707483781.759466][573348:573348] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483781.759520][573348:573348] CHIP:CTL: Setting attestation nonce to random value
[1707483781.759554][573348:573348] CHIP:CTL: Setting CSR nonce to random value
[1707483781.759845][573348:573350] CHIP:DL: CHIP task running
[1707483781.760018][573348:573350] CHIP:DL: HandlePlatformSpecificBLEEvent 32784
[1707483781.760289][573348:573350] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483781.760329][573348:573350] CHIP:CTL: Setting attestation nonce to random value
[1707483781.760477][573348:573350] CHIP:CTL: Setting CSR nonce to random value
[1707483781.761263][573348:573350] CHIP:CTL: Generating NOC
[1707483781.762228][573348:573350] CHIP:FP: Validating NOC chain
[1707483781.764293][573348:573350] CHIP:FP: NOC chain validation successful
[1707483781.764474][573348:573350] CHIP:FP: Updated fabric at index: 0x2, Node ID: 0x000000000001B669
[1707483781.764508][573348:573350] CHIP:TS: Last Known Good Time: 2023-04-11T06:55:26
[1707483781.764537][573348:573350] CHIP:TS: New proposed Last Known Good Time: 2021-01-01T00:00:00
[1707483781.764560][573348:573350] CHIP:TS: Retaining current Last Known Good Time
[1707483781.767451][573348:573350] CHIP:FP: Metadata for Fabric 0x2 persisted to storage.
[1707483781.770047][573348:573350] CHIP:TS: Committing Last Known Good Time to storage: 2023-04-11T06:55:26
[1707483781.772810][573348:573350] CHIP:CTL: Joined the fabric at index 2. Fabric ID is 0x0000000000000002 (Compressed Fabric ID: E2B270F8EA256EE6)
[1707483781.800711][573348:573350] CHIP:DL: Avahi browse: cache new
[1707483781.800865][573348:573350] CHIP:DL: Avahi browse: cache new
[1707483781.801071][573348:573350] CHIP:DL: Avahi browse: cache exhausted
[1707483782.802351][573348:573350] CHIP:DL: Avahi browse: all for now
[1707483782.804533][573348:573350] CHIP:DL: Avahi resolve found
[1707483782.804605][573348:573350] CHIP:DIS: Discovered node:
[1707483782.804625][573348:573350] CHIP:DIS:    Hostname: E89F6DE633D8
[1707483782.804648][573348:573350] CHIP:DIS:    IP Address #1: fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8
[1707483782.804668][573348:573350] CHIP:DIS:    Port: 5540
[1707483782.804686][573348:573350] CHIP:DIS:    Mrp Interval idle: not present
[1707483782.804704][573348:573350] CHIP:DIS:    Mrp Interval active: not present
[1707483782.804722][573348:573350] CHIP:DIS:    TCP Supported: 1
[1707483782.804740][573348:573350] CHIP:DIS:    Vendor ID: 5186
[1707483782.804758][573348:573350] CHIP:DIS:    Product ID: 4369
[1707483782.804775][573348:573350] CHIP:DIS:    Long Discriminator: 3840
[1707483782.804793][573348:573350] CHIP:DIS:    Pairing Hint: 36
[1707483782.804810][573348:573350] CHIP:DIS:    Instance Name: 20BF59E74C653CEF
[1707483782.804828][573348:573350] CHIP:DIS:    Commissioning Mode: 2
[1707483782.804855][573348:573350] CHIP:TOO: Discovered Device: fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8:5540
[1707483782.805610][573348:573350] CHIP:IN: SecureSession[0xffff9c00ce10]: Allocated Type:1 LSID:32431
[1707483782.805650][573348:573350] CHIP:SC: Assigned local session key ID 32431
[1707483782.805748][573348:573350] CHIP:EM: <<< [E:3533i S:0 M:256425147] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)
[1707483782.805796][573348:573350] CHIP:IN: (U) Sending msg 256425147 to IP address 'UDP:[fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8]:5540'
[1707483782.805954][573348:573350] CHIP:SC: Sent PBKDF param request
[1707483782.805990][573348:573350] CHIP:CTL: Setting attestation nonce to random value
[1707483782.806019][573348:573350] CHIP:CTL: Setting CSR nonce to random value
[1707483782.806061][573348:573350] CHIP:CTL: Commission called for node ID 0x0000000000000002
[1707483782.807037][573348:573350] CHIP:DL: Avahi resolve found
[1707483782.807112][573348:573350] CHIP:DIS: Discovered node:
[1707483782.807134][573348:573350] CHIP:DIS:    Hostname: E89F6DE633D8
[1707483782.807162][573348:573350] CHIP:DIS:    IP Address #1: fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8
[1707483782.807185][573348:573350] CHIP:DIS:    Port: 5540
[1707483782.807206][573348:573350] CHIP:DIS:    Mrp Interval idle: not present
[1707483782.807227][573348:573350] CHIP:DIS:    Mrp Interval active: not present
[1707483782.807248][573348:573350] CHIP:DIS:    TCP Supported: 1
[1707483782.807269][573348:573350] CHIP:DIS:    Vendor ID: 5186
[1707483782.807291][573348:573350] CHIP:DIS:    Product ID: 4369
[1707483782.807311][573348:573350] CHIP:DIS:    Long Discriminator: 3840
[1707483782.807332][573348:573350] CHIP:DIS:    Pairing Hint: 36
[1707483782.807353][573348:573350] CHIP:DIS:    Instance Name: 20BF59E74C653CEF
[1707483782.807377][573348:573350] CHIP:DIS:    Commissioning Mode: 2
[1707483783.001706][573348:573350] CHIP:EM: >>> [E:3533i S:0 M:109696304 (Ack:256425147)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1707483783.001813][573348:573350] CHIP:EM: Found matching exchange: 3533i, Delegate: 0xffff9c00f240
[1707483783.001899][573348:573350] CHIP:EM: Rxd Ack; Removing MessageCounter:256425147 from Retrans Table on exchange 3533i
[1707483783.002174][573348:573350] CHIP:EM: >>> [E:3533i S:0 M:109696305 (Ack:256425147)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:21 (SecureChannel:PBKDFParamResponse)
[1707483783.002248][573348:573350] CHIP:EM: Found matching exchange: 3533i, Delegate: 0xffff9c00f240
[1707483783.002305][573348:573350] CHIP:EM: CHIP MessageCounter:256425147 not in RetransTable on exchange 3533i
[1707483783.002394][573348:573350] CHIP:SC: Received PBKDF param response
[1707483783.002493][573348:573350] CHIP:SC: Peer assigned session ID 33675
[1707483783.016453][573348:573350] CHIP:EM: <<< [E:3533i S:0 M:256425148 (Ack:109696305)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:22 (SecureChannel:PASE_Pake1)
[1707483783.016617][573348:573350] CHIP:IN: (U) Sending msg 256425148 to IP address 'UDP:[fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8%eth0]:5540'
[1707483783.016805][573348:573350] CHIP:SC: Sent spake2p msg1
[1707483783.093431][573348:573350] CHIP:EM: >>> [E:3533i S:0 M:109696306 (Ack:256425148)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:10 (SecureChannel:StandaloneAck)
[1707483783.093534][573348:573350] CHIP:EM: Found matching exchange: 3533i, Delegate: 0xffff9c00f240
[1707483783.093618][573348:573350] CHIP:EM: Rxd Ack; Removing MessageCounter:256425148 from Retrans Table on exchange 3533i
[1707483783.807318][573348:573350] CHIP:EM: >>> [E:3533i S:0 M:109696307 (Ack:256425148)] (U) Msg RX from 0:0000000000000000 [0000] --- Type 0000:23 (SecureChannel:PASE_Pake2)
[1707483783.807421][573348:573350] CHIP:EM: Found matching exchange: 3533i, Delegate: 0xffff9c00f240
[1707483783.807486][573348:573350] CHIP:EM: CHIP MessageCounter:256425148 not in RetransTable on exchange 3533i
[1707483783.807584][573348:573350] CHIP:SC: Received spake2p msg2
[1707483783.810849][573348:573350] CHIP:SC: Failed to verify peer's MAC. This can happen when setup code is incorrect.
[1707483783.810928][573348:573350] CHIP:SC: Sending status report. Protocol code 2, exchange 3533
[1707483783.811047][573348:573350] CHIP:EM: <<< [E:3533i S:0 M:256425149 (Ack:109696307)] (U) Msg TX to 0:0000000000000000 [0000] --- Type 0000:40 (SecureChannel:StatusReport)
[1707483783.811346][573348:573350] CHIP:IN: (U) Sending msg 256425149 to IP address 'UDP:[fd61:3599:e3a1:0:ea9f:6dff:fee6:33d8%eth0]:5540'
[1707483783.811757][573348:573350] CHIP:IN: SecureSession[0xffff9c00ce10]: Released - Type:1 LSID:32431
[1707483783.811847][573348:573350] CHIP:SC: Failed during PASE session setup: src/crypto/CHIPCryptoPALOpenSSL.cpp:1437: CHIP Error 0x000000AC: Internal error
[1707483783.811933][573348:573350] CHIP:TOO: Secure Pairing Failed
[1707483783.812034][573348:573350] CHIP:TOO: Pairing Failure: src/crypto/CHIPCryptoPALOpenSSL.cpp:1437: CHIP Error 0x000000AC: Internal error
[1707483783.812417][573348:573348] CHIP:CTL: Shutting down the commissioner
[1707483783.812486][573348:573348] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483783.812605][573348:573348] CHIP:CTL: Shutting down the controller
[1707483783.812672][573348:573348] CHIP:IN: Expiring all sessions for fabric 0x2!!
[1707483783.812724][573348:573348] CHIP:FP: Forgetting fabric 0x2
[1707483783.812790][573348:573348] CHIP:TS: Pending Last Known Good Time: 2023-04-11T06:55:26
[1707483783.813178][573348:573348] CHIP:TS: Previous Last Known Good Time: 2023-04-11T06:55:26
[1707483783.813302][573348:573348] CHIP:TS: Reverted Last Known Good Time to previous value
[1707483783.813396][573348:573348] CHIP:CTL: Shutting down the commissioner
[1707483783.813450][573348:573348] CHIP:CTL: Stopping commissioning discovery over DNS-SD
[1707483783.813501][573348:573348] CHIP:CTL: Shutting down the controller
[1707483783.813549][573348:573348] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
[1707483783.815702][573348:573348] CHIP:DMG: All ReadHandler-s are clean, clear GlobalDirtySet
[1707483783.815900][573348:573348] CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
[1707483783.816031][573348:573348] CHIP:FP: Shutting down FabricTable
[1707483783.816107][573348:573348] CHIP:TS: Pending Last Known Good Time: 2023-04-11T06:55:26
[1707483783.816422][573348:573348] CHIP:TS: Previous Last Known Good Time: 2023-04-11T06:55:26
[1707483783.816607][573348:573348] CHIP:TS: Reverted Last Known Good Time to previous value
[1707483783.817179][573348:573348] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-r1J02I)
[1707483783.818968][573348:573348] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1707483783.819123][573348:573348] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
[1707483783.819184][573348:573348] CHIP:DL: Inet Layer shutdown
[1707483783.819238][573348:573348] CHIP:DL: BLE shutdown
[1707483783.819285][573348:573348] CHIP:DL: System Layer shutdown
[1707483783.819662][573348:573348] CHIP:TOO: Run command failure: src/crypto/CHIPCryptoPALOpenSSL.cpp:1437: CHIP Error 0x000000AC: Internal error
```
The following DUT log also show there is some communication, so I would assume discovery works:
```
0
I (6049572) chip[EM]: >>> [E:50682r S:0 M:139786413] (U) Msg RX from 0:039AD38E69641ACD [0000] --- Type 0000:20 (SecureChannel:PBKDFParamRequest)
I (6049582) chip[EM]: <<< [E:50682r S:0 M:109696313 (Ack:139786413)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[FD61:3599:E3A1::1C2%st1]:40090] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (6049602) chip[EM]: <<< [E:50682r S:0 M:109696314 (Ack:139786413)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[FD61:3599:E3A1::1C2%st1]:40090] --- Type 0000:21 (SecureChannel:PBKDFParamResponse)
I (6049612) chip[SVR]: Commissioning session establishment step started
I (6049672) chip[EM]: >>> [E:50682r S:0 M:139786414 (Ack:109696314)] (U) Msg RX from 0:039AD38E69641ACD [0000] --- Type 0000:22 (SecureChannel:PASE_Pake1)
I (6049672) chip[EM]: I (6049682) app_task: window 0 identification remaining time: -1 (segments: 0x0)
<<< [E:50682r S:0 M:109696315 (Ack:139786414)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[FD61:3599:E3A1::1C2%st1]:40090] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (6050412) chip[EM]: <<< [E:50682r S:0 M:109696316 (Ack:139786414)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[FD61:3599:E3A1::1C2%st1]:40090] --- Type 0000:23 (SecureChannel:PASE_Pake2)
E (6050422) chip[DL]: Long dispatch time: 750 ms, for event type 3
I (6050502) chip[EM]: >>> [E:50682r S:0 M:139786415 (Ack:109696316)] (U) Msg RX from 0:039AD38E69641ACD [0000] --- Type 0000:40 (SecureChannel:StatusReport)
E (6050502) chip[SC]: Received error (protocol code 2) during PASE process: 38
E (6050512) chip[SC]: Failed during PASE session setup: 38
E (6050522) chip[SVR]: Commissioning failed (attempt 1): 38
I (6050522) chip[DIS]: Updating services using commissioning mode 2
I (6050532) chip[DIS]: CHIP minimal mDNS started advertising.
I (6050562) chip[DIS]: Advertise operational node 49B67B9CEE0369C6-0000000000000001
I (6050562) chip[DIS]: CHIP minimal mDNS configured as 'Operational device'; instance name: 49B67B9CEE0369C6-0000000000000001.
I (6050572) chip[DIS]: mDNS service published: _matter._tcp
I (6050582) chip[DIS]: Advertise commission parameter vendorID=5186 productID=4369 discriminator=3840/15 cm=2
I (6050592) chip[DIS]: CHIP minimal mDNS configured as 'Commissionable node device'; instance name: 9226558D0001A7B7.                                                    0601,2404(SEGW),01:00000001
I (6050612) chip[DIS]: mDNS service published: _matterc._udp
I (6050612) chip[EM]: <<< [E:50682r S:0 M:109696317 (Ack:139786415)] (U) Msg TX to 0:0000000000000000 [0000] [UDP:[FD61:3599:E3A1::1C2%st1]:40090] --- Type 0000:10 (SecureChannel:StandaloneAck)
I (6050622) app_main: Commissioning window opened
```

**Comment by VaishaliAvhale** [comment]
Please attach the complete log files. It would be helpful for debugging. Also, please find the attached ACE-1.5 test case steps. Re-execute the test case and share the log files if you face any issues.
[TC-ACE-1_5_Steps.ods](https://github.com/espressif/esp-matter/files/14359223/TC-ACE-1_5_Steps.ods)

**Comment by PhLuReh** [comment]
I ran the steps from you specification, which resulted in the following logs:
[2024-02-22-TC-ACE-1_5_chip-tool.log](https://github.com/espressif/esp-matter/files/14370524/2024-02-22-TC-ACE-1_5_chip-tool.log)
[2024-02-22-TC-ACE-1_5_DUT.log](https://github.com/espressif/esp-matter/files/14370525/2024-02-22-TC-ACE-1_5_DUT.log)
```
./chip-tool pairing open-commissioning-window 1 1 400 2000 3841 > 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool pairing code 2 35163245584 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool operationalcredentials read current-fabric-index 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": [{ "cluster": 31, "endpoint": 0, "deviceType": null }]}, {"fabricIndex": 1, "privilege": 1, "authMode": 2, "subjects": null, "targets": [{ "cluster": 29, "endpoint": 0, "deviceType": null }]}]' 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool descriptor read device-type-list 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool basicinformation read vendor-id 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool descriptor read device-type-list 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool basicinformation read vendor-id 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}]' 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool descriptor read device-type-list 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
./chip-tool operationalcredentials remove-fabric 2 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
```

The `read device-type-list` step fails as it can successfully read the device types, but should fail. Don't know why, are there any ACLs wrongly configured? Or is there something not inited correctly?

**Comment by VaishaliAvhale** [comment]
Could you please attach the chip-tool logs containing the chip-tool command you executed? It would be helpful for me to debug. Additionally, please provide the commit IDs for the esp-matter release/v1.1 branch, esp-idf, and connectedhomeip.

On my end, I tested with:

esp-matter: release/v1.1 branch, commit ID: 5abc3095da0da9342dcd1250a01d2c47f840fed0
esp-idf: v5.1.1, commit ID: e088c3766ba440e72268b458a68f27b6e7d63986
connectedhomeip: release/v1.1 branch
All steps executed as expected. Please take a look at the attached logs.
[TC-ACE-1-5-chip-tool.log](https://github.com/espressif/esp-matter/files/14374136/TC-ACE-1-5-chip-tool.log)
[TC-ACE-1.5-DUT.log](https://github.com/espressif/esp-matter/files/14374138/TC-ACE-1.5-DUT.log)

**Comment by PhLuReh** [comment]
I knew you would request for this... No problem, here's the combined file
[2024-02-22-TC-ACE-1_5_chip-tool.log](https://github.com/espressif/esp-matter/files/14375042/2024-02-22-TC-ACE-1_5_chip-tool.log)
[2024-02-22-TC-ACE-1_5_DUT.log](https://github.com/espressif/esp-matter/files/14375045/2024-02-22-TC-ACE-1_5_DUT.log)

ESP-Matter commit b2a6701ac6f41a2fdd1549b37f4b58aeab6e0b11
ESP-IDF commit e088c3766ba440e72268b458a68f27b6e7d63986
connectedhomeip commit 181b0cb14ff007ec912f2ba6627e05dfb066c008
Test runs were executed on Version: v2.8.1-official Sha: 1446f09

**Comment by PhLuReh** [comment]
Just saw, that I was not developing on the release/v1.1 as I expected. Something with my docker container went wrong. Still waiting for the v1.1 docker image https://github.com/espressif/esp-matter/issues/756#issuecomment-1938392188

**Comment by VaishaliAvhale** [comment]
1] Commission TH1
 2] ./chip-tool pairing open-commissioning-window 1 1 400 2000 3841 > 2024-02-22-TC-ACE-1_5_chip-tool.log
 3] ./chip-tool pairing code 2 35163245584 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
 4] ./chip-tool operationalcredentials read current-fabric-index 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
 5] ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": [{ "cluster": 31, "endpoint": 0, "deviceType": null }]}, {"fabricIndex": 1, "privilege": 1, "authMode": 2, "subjects": null, "targets": [{ "cluster": 29, "endpoint": 0, "deviceType": null }]}]' 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
6]  ./chip-tool accesscontrol write acl '[{"fabricIndex": 2, "privilege": 5, "authMode": 2, "subjects": [223344], "targets": [{ "cluster": 31, "endpoint": 0, "deviceType": null }]}, {"fabricIndex": 2, "privilege": 1, "authMode": 2, "subjects": null, "targets": [{ "cluster": 40, "endpoint": 0, "deviceType": null }]}]' 2 0 --commissioner-name beta
7] ./chip-tool descriptor read device-type-list 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
8] ./chip-tool basicinformation read vendor-id 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
9] ./chip-tool descriptor read device-type-list 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
10] ./chip-tool basicinformation read vendor-id 2 0 --commissioner-name beta >> 2024-02-22-TC-ACE-1_5_chip-tool.log
11] ./chip-tool accesscontrol write acl '[{"fabricIndex": 1, "privilege": 5, "authMode": 2, "subjects": [112233], "targets": null}]' 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log
12] ./chip-tool operationalcredentials remove-fabric 2 1 0 >> 2024-02-22-TC-ACE-1_5_chip-tool.log

Hi @PhLuReh, I looked into the shared logs and found that you missed executing Step 6, 'access control write,' for endpoint 2.

**Comment by VaishaliAvhale** [comment]
Yes this TestCase Passed Successfully!
Checked logs sent by you and each steps response is according to the spec.

**Comment by PhLuReh** [comment]
Thank you @VaishaliAvhale !!

**Comment by VaishaliAvhale** [comment]
Hi @PhLuReh, as TC-ACE-1.5 has been executed successfully on your end, could you please close this issue?

**Comment by PhLuReh** [comment]
@stefano055415 could you also succeed with these manual steps? so you could close it (I'm not allowed to do so)

**Comment by dhrishi** [comment]
Closing this now
