### ISSUE TITLE
TC-RR-1.1 Constrain Error (CON-1074)

### ISSUE THREAD

**Issue by PhLuReh** [espressif/esp-matter#862]
**Describe the bug**
In TC-RR-1.1 from python_testing library the `Node-Label` of the `BasicInformation` cluster is written with the sequence `Before Subscriptions 12345678912`. This one is 32 characters long. It results in the failure:
```
IM Error 0x00000587: General error: 0x87 (CONSTRAINT_ERROR)
```

If I shorten the sequence by 1 it writes with `SUCCESS`. I read through the spec, an the maximum length is set to 32. But the situation is really unclear (from Matter 22-27349-002_Matter-1.1-Core-Specification.pdf):
> Note that the character string type is a bounded sequence of characters whose size bound format is
not specified in the data model, but rather a property of the underlying encoding. Therefore, no
assumptions are to be made about the presence or absence of a length prefix or null-terminator
byte, or other implementation considerations.

What should we do? Am I the first one running this test?

**Environment**
ESP-Matter commit f511d226420f56a0565f7b147ebc399f88afc3ce
ESP-IDF commit e088c3766ba440e72268b458a68f27b6e7d63986
connectedhomeip commit 32992decc576355eb7bedc97c3e18c8efdd58e6c
SOC: ESP32
Host Machine OS: `Linux version 6.1.29-1-MANJARO (builduser@fv-az292-908) (gcc (GCC) 12.2.1 20230201, GNU ld (GNU Binutils) 2.40) #1 SMP PREEMPT_DYNAMIC Wed May 17 14:00:55 UTC 2023`
- Commissioner app and versions if present: chip-tool from official TH v2.8.1-official
- Commissioner's logs if present:
[20240307-TC-RR-1_1-chiptool.log](https://github.com/espressif/esp-matter/files/14526936/20240307-TC-RR-1_1-chiptool.log)

**Comment by shubhamdp** [comment]
@PhLuReh can you please try this on main branch, we have pushed out the change https://github.com/espressif/esp-matter/commit/d481fa9cf1d09001b1bbd9cd59dbb7836bbb13fe

**Comment by shubhamdp** [comment]
And backports for release/v1.1 and release/v1.2 will be out soone

**Comment by PhLuReh** [comment]
Ok, thanks, that was quit, but I need to wait for release/v1.1.

**Comment by shubhamdp** [comment]
@PhLuReh changes are ready, but having some other troubles, getting mainline, I'll give you a patch till that time. Hopefully this patch will be mainlined by today or tomorrow.
[657.patch](https://github.com/espressif/esp-matter/files/14571276/657.patch)

**Comment by PhLuReh** [comment]
I uploaded the firmware to the device, but neither mine nor your patch is working. Still getting the `CONSTRAINT_ERROR` with the chip-tool. I again read through the sources but I'm missing the point where the check is done. I only found a [hint in the source](https://github.com/espressif/esp-matter/commit/d481fa9cf1d09001b1bbd9cd59dbb7836bbb13fe#diff-bbcdfd73515b0a83a72d43ef8f0b9186e05a064f8f4b7f524de6cac0dc521a4bR158):
```
    // The size in the attribute metadata remains constant and is verified during write operations.
    uint16_t max_val_size;
```
Doesn't the write operation also need a patch?

**Comment by shubhamdp** [comment]
> Doesn't the write operation also need a patch?

This check happens in `attribute_storage.cpp`.

Which attribute are you trying to write?

**Comment by PhLuReh** [comment]
I was just referring to the commend inside the code, which says `verified during write operations`.

> This check happens in `attribute_storage.cpp`.
`attribute_storage.cpp` is not part of the patch, nor of the commit?

The chip-tool log is still the same. I try to send a DUT-log in 3 hours.

**Comment by shubhamdp** [comment]
Thanks @PhLuReh for testing this out, I found the problem, it was fixed onwards v1.2 and was not backported, https://github.com/espressif/esp-matter/commit/28b37dea29476f1d6c27a02f02f130aaa31ecc1c.

This occurs after first reboot.

**Comment by PhLuReh** [comment]
Thanks for pointing this out. For those who are searching for it, I found the [corresponding lines](https://github.com/espressif/esp-matter/blob/1cb7b39096a6453a4dc4f6eb0c3d78218231c842/components/esp_matter/esp_matter_core.cpp#L1538) in `esp_matter_core.cpp` (looks like it was refactored in v1.2).

With patch 657 and the fix in 28b37de, I'm still not able to write 32 characters, only 31:
[202403141352_TC-RR-1_1-chiptool.txt](https://github.com/espressif/esp-matter/files/14602429/202403141352_TC-RR-1_1-chiptool.txt)
[202403141352_TC-RR-1_1-DUT.txt](https://github.com/espressif/esp-matter/files/14602430/202403141352_TC-RR-1_1-DUT.txt)

I still do not know, where `attribute->max_val_size` get's checked on write access - and I think this is the problem.

**Comment by shubhamdp** [comment]
@PhLuReh  You would still need the [657.patch](https://github.com/espressif/esp-matter/files/14571276/657.patch)

**Comment by shubhamdp** [comment]
Sorry for all the fuzz. I tried following and it works in both first boot and after every boot. can you please try  --> git am [str-attr-fix.patch](https://github.com/espressif/esp-matter/files/14605982/str-attr-fix.patch).

esp-matter: f511d226420f56a0565f7b147ebc399f88afc3ce

```
chip-tool basicinformation write node-label "01234567890123456789012345678901" 1 0
```
[chip-tool.log](https://github.com/espressif/esp-matter/files/14606021/chip-tool.log)

**Comment by PhLuReh** [comment]
As `git am` was new to me, this was the output, after checking out heat of the previously patched files:
```
Applying: Fix problems with string type attributes
Applying: Fix active locale attributes
Applying: Fix the return type for invalid event id
Applying: Fix CI building for esp-now bridge
Applying: update the size after updating total size
```

I now also ran the original code from the test and both are returning `SUCCESS` now:
```
./chip-tool basicinformation write node-label "Before Subscriptions 12345678912" 1 0
```

Will there still be effort to merge this into `release/v1.1`?

**Comment by shubhamdp** [comment]
Thanks @PhLuReh for your confirmation. This patch is merged to [release/v1.1](https://github.com/espressif/esp-matter/commit/6b828085573abaa8065d6c2eace96f8188b42023).
